POST http://localhost:3000/auth
Content-Type: application/json

{
  "email": "b@mail.com",
  "name": "Any Name",
  "role": "User",
  "password": "rubinoobrabo",
  "jobTitle": "Assessor",
  "departament": "ProjetosComputação"
}

### 

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "b@mail.com",
  "password": "rubinoobrabo"
}

###
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX2lkIjoiQkl0NExUZ1RGSG82VmRxSlZnbFoiLCJlbWFpbCI6ImJAbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImlhdCI6MTczMDgxOTA3OSwiZXhwIjoxNzMwODIyNjc5fQ.5v0oubvxPhv9pgR6m1myDLNtd0aw2sLqcotWLj7nr_8
